#!/bin/bash

pkill xfsettingsd
cd /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/
sudo mv ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml .
sudo mv ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml .
sed -i '/<channel name="xfce4-panel"/c\<channel name="xfce4-panel" version="1.0" locked="*" unlocked="root">' xfce4-panel.xml
sed -i '/<channel name="xfce4-desktop"/c\<channel name="xfce4-desktop" version="1.0" locked="*" unlocked="root">' xfce4-desktop.xml
